language: minimal
dist: xenial
cache:
  apt: true
  timeout: 1000 #In seconds
  directories:
  # - $TRAVIS_BUILD_DIR/firesim-riscv-tools-prebuilt
  - $TRAVIS_BUILD_DIR/riscv
  - $TRAVIS_BUILD_DIR/linux
  - $TRAVIS_BUILD_DIR/qemu

git:
  submodules: false
  depth: 1

env:
  - RISCV=$TRAVIS_BUILD_DIR/riscv PATH=$PATH:$RISCV/bin

addons:
  apt:
    packages:
    - expect
    - autoconf
    - automake
    - autotools-dev
    - bc
    - bison
    - build-essential
    - curl
    - expat
    - libexpat-dev
    - flex
    - gawk
    - gcc
    - git
    - gperf
    - libgmp-dev
    - libmpc-dev
    - libmpfr-dev
    - libtool
    - texinfo
    - tmux
    - patchutils
    - zlib1g-dev
    - wget
    - bzip2
    - patch
    - vim-common
    - lbzip2
    - python
    - pkg-config
    - libglib2.0-dev
    - libpixman-1-dev
    - libssl-dev
    - makeself
    - unzip

branches:
  only:
    - dev
    - master


before_install:
  - git submodule init -- linux
  - git submodule init -- qemu
  - if [ -d "linux/.git" ]; then ls; else git clone --shallow-since=2018-05-01 https://github.com/torvalds/linux linux; fi
  - if [ -d "qemu/.git" ]; then ls; else git clone --shallow-since=2018-05-01 https://github.com/qemu/qemu qemu; fi
  - git submodule update --depth=1 -- linux
  - git submodule update --depth=1 -- qemu
  - ./fast-setup.sh
  - cp -r linux/.git linux-git
  - cp -r qemu/.git qemu-git

jobs:
  include:
    - stage: cache warmup
      script: true
      after_failure:
        - ls -al
        - cat firesim-riscv-tools-prebuilt-*/riscv-tools-install.log
    - stage: build everything & test
      script:
        - source ./source.sh
        - mkdir build
        - cd build
        - cmake ../
        - travis_wait 120 make -j3
        - travis_wait 10 make run-tests
        - cd ..
        - cd qemu; git clean -fxd > /dev/null;git reset --hard > /dev/null;rm -rf .git;mv ../qemu-git  .git;cd ..
        - cd linux;git clean -fxd > /dev/null;git reset --hard > /dev/null;rm -rf .git;mv ../linux-git .git;cd ..
      after_failure:
        - cat screenlog.0
        - cat output.log
    - stage: build (sifive)
      script:
        - source ./source.sh
        - mkdir build
        - cd build
        - cmake -DLINUX_SIFIVE=y -DSM_PLATFORM=fu540 ../
        - travis_wait 120 make -j3
        - cd ..
        - cd qemu; git clean -fxd > /dev/null;git reset --hard > /dev/null;rm -rf .git;mv ../qemu-git  .git;cd ..
        - cd linux;git clean -fxd > /dev/null;git reset --hard > /dev/null;rm -rf .git;mv ../linux-git .git;cd ..
